### ISSUE TITLE
Antenna Dear

### ISSUE THREAD

**Issue by supernative** [supernative/script#1]

**Comment by supernative** [comment]
I don't like any of the simulation stuff that you would find everywhere with their top notch suits and all, because i am neither rich nor idiot.

So I shall use the universe as my calculator and strictly that! Also I do not want to concern myself with continuum of existence in the classical view of the universe because they are not classical but continuous though, except at the quantum view of the world.

It means:

- no infinitesimal approximation over planck's territory
- mechanical evolution of the quantities that only exists classically and statically without any regard for the other dynamical functions
- no special treatment of time axis
- no single valued observables

So what does make it:

- discrete substrate in space and time
- principle based assertions such as the principle of locality
- constraining other laws via our programming
- two level density operators
- reversible computation all across
- no mention of initial condition or laws of motion
- bold claims (conjecture) and assertions rather than empirical facts
- dual constitution of configuration space that does NOT deal with physical phenomena but the physical regularities that are expressed in terms of dichotomies
- special attention to the setting up of dichotomy in experimental contexts
- insistence on the testability and refutability
- laws expressed in terms of geometrical objects or constructor theoretic statements


**Constructor Theoretic Statements In Place of Possible Governing Laws Or Everything Unknown**

We do not have to keep a good record of the instances that we attempted to think about a problem and therefore hold a bookkeeping position concerning those temporarily kept by them. Rather it is our duty to solve the damn problem, for it just pains the people who would otherwise not feel as such, had we always done that throughout the history.

Problems are there to be solved. (DD) Indeed!

A statement about reality is an expression over the possible ways that one can get affected by their relationship.

**Comment by supernative** [comment]
**Possible Service Error and Other For NonNative**

_integer_ : alias used in referring to the service

List of services:

- `sample` : getting response for query sent
- `inject` : sending query message to the server
- `reject` : violation in service requested
- `configure` : dictionary valued key-value parameters
- `update` : change to the dictionary
- `prepare` : instantiation of locally available service privileges
- `misc` : other utility services

```misc
upload or delete or use : file level operators
create or load or store : ordered model specific object systems
view or select or confirm : requesting details of the features
```

**Targeted Programming and Intrinsic Development**

`sample` allows for generic communication with the server while the detailed processing happens locally.

`cost` is not included yet, but should be made available by default.

`statistics` is not yet available, but must create a comprehensive report of the interaction.

`determination` is the program responsible for selecting the application specific parameters.

`straight` is a type of record we must keep locally that has to cover all of history, until higher level processing emerges.

**Comment by supernative** [comment]
**Trial and Error Discovery of Policy**

Given a set of resources, find the best policy at all time.

This policy is used to optimize the driving cost and total available randomness.

There is a finite number of possible configurations and their even stricter set of permutations. All of which could be discovered into a deterministic environment.

**Comment by supernative** [comment]
**Design of an Unintelligent Machine**

We are looking for a deterministic policy.

This policy will discover all the possible ways some set of attributes can be ordered and their complete permutation possibilities.

Once we achieve that data, the policy will be the function of that data over the set of real attributes.

Real attributes are those quantities which is expected by the system implementing some subset of those attributes and the policy shall directly affect what property of the system gets to evolve forward.

**Objective Functionals**

_accessible_ : set of available features that isn't intrinsic completely
_incorporated_ : set of intrinsic features that correctly mirrors the actual content
_compounded_ : set of fully managed criterion resulting from transformation of extrinsic resources

**Comment by supernative** [comment]
**Task**

Go to the website and look at all those pages related to (that) purpose.

Since I am going about this (path), you should learn all the things you can find on that vacation art.

Build a nice policy that doesn't drive you to the unrelated destination.

Good luck on your journey.

**Comment by supernative** [comment]
> **Task**
> 
> Go to the website and look at all those pages related to (that) purpose.
> 
> Since I am going about this (path), you should learn all the things you can find on that vacation art.
> 
> Build a nice policy that doesn't drive you to the unrelated destination.
> 
> Good luck on your journey.

Your policy will be exclusively used in the process (that one).

As you will learn that all those things are at play in here.

Your policy should also include the visits to the factory from time to time in order of gauge what's going to go wrong with your product.

**Comment by supernative** [comment]
What is a policy?

An institutional structure establishing a set of standards that will be used and when it becomes necessary to implement, it will have to follow those norms that govern how the agency operates.

**So** it is:
- a set of ordered pairs of attributes
- a defined relationship between the query generator and the property enabled by default
- a set of unquestioned functions
- a host of qualifying tasks
- a system of guiding invariance

When it must be used, all the usage will consist of accessing the dictionary at some point via an existing key, then through queries that would match another such function.

**Comment by supernative** [comment]
Where would be used!

- Who drives the policy?
- Which policy is being sought?
- by whom do the policies have been made to work?

**Realizable Numbers**

It is different from the classical computable numbers.

I want to define a set of static states of a computer with each positive real number greater than 0 being in one and all numbers smaller than 0 at the other. Let the two set have no intrinsic properties together.

In programming the two sets, none of its properties must interact with any other data types without explicitly defined exception sets.

**Sign/Exponent/Mantissa**

None of these are necessary in my model.

**Gravitizing Quantum Mechanics and Quantizing Gravity**

- observer and instrument is entangled deeply
- mass displacement and correspondence is necessarily recorded
- shape and size displacement is unitary with respect to weight of the timer

**Instantangent**

If x is some set of displacements, y is the corresponding values associated with that set, and z remains as whatever the association requires it to be, then we need to know what the quantity t evolves with our setup.

Let the sine of x be the distance ever covered and cosine of x be those reversible unit changes per covered unit be the y components.

Tangent of x is then the ratio of signed and co-signed values.

y depends on x by that factor or x changes with that amount being constant across all y associated.




And if the union of the two different episodes with their respective sets have the same constant then the arctangent of t is z as x —> infinity (anywhere) and tangent to the z will live forever within the pi / 2 range (everywhere), so long it's unity at the plane.

Then, hyperbolic quantities are subjected to those arc cycles correlates directly and it has the tangent effect that brings quantities that rolls with the infinities back the range (-1, 1).

**Comment by supernative** [comment]
> Where would be used!
> 
> - Who drives the policy?
> - Which policy is being sought?
> - by whom do the policies have been made to work?
> 
> **Realizable Numbers**
> 
> It is different from the classical computable numbers.
> 
> I want to define a set of static states of a computer with each positive real number greater than 0 being in one and all numbers smaller than 0 at the other. Let the two set have no intrinsic properties together.
> 
> In programming the two sets, none of its properties must interact with any other data types without explicitly defined exception sets.
> 
> **Sign/Exponent/Mantissa**
> 
> None of these are necessary in my model.
> 
> **Gravitizing Quantum Mechanics and Quantizing Gravity**
> 
> - observer and instrument is entangled deeply
> - mass displacement and correspondence is necessarily recorded
> - shape and size displacement is unitary with respect to weight of the timer
> 
> **Instantangent**
> 
> If x is some set of displacements, y is the corresponding values associated with that set, and z remains as whatever the association requires it to be, then we need to know what the quantity t evolves with our setup.
> 
> Let the sine of x be the distance ever covered and cosine of x be those reversible unit changes per covered unit be the y components.
> 
> Tangent of x is then the ratio of signed and co-signed values.
> 
> y depends on x by that factor or x changes with that amount being constant across all y associated.
> 
> 
> 
> 
> And if the union of the two different episodes with their respective sets have the same constant then the arctangent of t is z as x —> infinity (anywhere) and tangent to the z will live forever within the pi / 2 range (everywhere), so long it's unity at the plane.
> 
> Then, hyperbolic quantities are subjected to those arc cycles correlates directly and it has the tangent effect that brings quantities that rolls with the infinities back the range (-1, 1).
> 
> 
> **Static, Dynamic and Constitutionals**
> 
> - [ ] Conserved files
> - [ ] Shared files
> 
> Conserved files have quantities in terms of amplitudes that shared files cannot change under any configuration of the disk.
> 
> Shared files are transformed anywhere but arrives at the disk eventually.
> 
> _static constitution_ : prepares the disk content in a way that keeps the immutable memory intact regardless of what happens to the rest of the computer
> 
> _dynamic configuration_ : computation on a specified constitution of data available somewhere also specified (or asserted)
> 
> A state is the description of the computer, followed by an explanation.
> 
> Consider a rectangular object programmed from generically assembled bits:
> 
> - it has four corners labeling computation, preparation, measurement and other construction any way possible
> - it has two approachable midpoints from both of the long sides
> - it remains in parallel with the long sides perpendicular to the line connecting the sides always passing through the middle position exactly at one point whenever there are two possible approaches possible. given the object
> 
> **Encoding/Decoding Algorithm**
> 
> Continuing from the rectangled state, any program can reach any other program, provided that the static constitution of the module giving structure the search had at least one of the midpoints that its parameter group could approach.
> 
> Let _ħ_ be the smallest difference possible.
> 
> The limit of the encoder function for the approaches given as input + h and h applying the transfer over to the other side causing an output.
> 
> Here are some requirements:
> 
> - [ ] specifying the named quantities
> - [ ] quantization of the bit depth
> - [ ] permutation order attachment
> - [ ] offloading to substrate location
> 
> 
> Here are the next immediate tasks:
> 
> I'll setup two types of files anywhere in the computer.
> 
> Of the two files, î will write a process that keeps it at certain level.
> 
> The other program can change, however the possible change that can be combined into a third file will be determined.
> 
> - [ ] Runtime length and buffer length
> - [ ] Constructor program and copier script
> 
> Use _MuLaw_ to encode and decode with constant number of quantization channels.
> 
> Every track will be used in a stereo setting and one of the channel reversing its pole to match the consistency required.
> 
> - [ ] Number of points to consider
> - [ ] Number of locations to sample
> - [ ] Descriptor of x
> - [ ] Constructor of y
> 
> ```catalyst
> _u_ : _description(x)_ —> _x_
> _c_ : _description(x)_ —> _description(x)_
> ```
> 
> When _x_ is looking for some _y_ which is dependent on _z_ that is effected by _t_ then the _description(x)_ is the description of y having been found by x and _rho_ is the magnitude of that search in radial term which gives off _phi_ whenever _z_ affects some quantity _theta_ that directly influences what _description(c)_ could be for _c_ describing _t_ via the normal condition respective of the description _phi_ would have of _description(theta)_ that y gets directly transformed into and finally _description(t)_ causing _-t_ to propagate the resulting information back to _x_ which remains grounded by the search.

**Denotation and Programming**

```python
stack = rand(n, k) # n being the quantizers and k is the frames to unity

stereo = compile(stack, file) # mixes the stack variables and stores the output to file given

```

Should stereo object have three dimensional tensor form?

Meaning the components are though described in terms of two dimensional track amplitudes, the construct of the amplitude is lives in 3D.

**Comment by supernative** [comment]
**Reaction System**

There are _M_ molecules and a subset of that set is _r_ with _(A, B)_ pairs of representative proportions.

The pairs cause the following reaction:

`a[1] + a[2], ..., + a[k] —> b[1] + b[2] + ..., b[k]`

_r_ is the reaction among another set _R_ which denotes the allowable set of proportions.

The system is a pair _(M, R)_ called **reaction system**.

Define some set _C_ denoting the constitution _{(m, r) | m in M, r in R}_ for all pairs of reactive centers that can participate in the reaction process.

_g_ is the generic resource available in the environment, let this be a proper subset of the set _M_.

Let _r'_ be another proper subset of _R_.

Define _closure_ of the generic resourcefulness of the states of _g_ with respect to the set of reaction dependent on the states of that substrate be _closure[r'](g)_.

That is all the reactions that could only be caused from the resource sampled and all molecules that could be instantiated starting only from that derivative actions.

Since every catalysis denotes its effect in the reaction it caused, I shall program the set of counterfactual information as follows:

- [ ] Describe what apparently can be possible
- [ ] Describe what theoretically cannot be described
- [ ] Put the two things in a stereo type setting
- [ ] Bring the copy over to the next description

If the copy is possible, the theory is false and the copy should contribute to the negation of the description. Then the next set of description will involve the stereo type that destroys the effect of the false theory while mixing with the description (having been stereo typed into existence) causing the effect of the corresponding theory (that which refers to this to bring about its independent existence and effects).

**Comment by supernative** [comment]
> Main topics are `antenna[lobe, pole[0, 1], radiation, directivity]`, polar diagrams for different patterns, `link[between, antenna, microphone]`, `unitary[language, program, environment, others]`, `number[dust, called(physics)]`, physical models being too classical and heavily inaccurate, `phantom[group, circuit]`, `balance[condition, simplex]`, `optimization[side, mid, transformer[winding, core[[magnetic, current], flux], ~winding], line]`, boolean observables etc.


Lobes are contours you get when you map out the radial distances available from the roots of your antenna function.

Radiation is the propagating wave from a field that spreads with the magnitude of the radius defining the scope of the field.
